services:
  app:
    container_name: apirust
    build:
      context: ./api-rust
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@database:5432/postgres 
    tty: true
    restart: always
    depends_on:
      - database
      #- redis
    ports: 
      - '8080:8080'
    volumes:
      - .:/app  
    env_file: api-rust/.env
#    environment:
    networks:
      - rustnet

  database:
    container_name: database
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5437:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rustnet
#  redis:
#    image: redis:7.2.4-alpine
#    ports:
#      - '6379:6379'

volumes:
  db_data:

networks:
  rustnet:
    driver: bridge